SELECT [Sub_SubjectNo]
      ,[Sub_SubjectName]
      ,[Sub_SubjectTitle]
      ,[Sub_Units]
      ,[Sub_LecHours]
      ,[Sub_LabHours]
  FROM [DB_Scheduling].[dbo].[CTU_Subject]
  WHERE Sub_SubjectName = 'GEC-LWR' 
		Or Sub_SubjectName = 'GEC-E'
		Or Sub_SubjectName = 'PE 1'
		Or Sub_SubjectName = 'GEC-TCW'
		Or Sub_SubjectName = 'GEC-AA'
		Or Sub_SubjectName = 'GEC-PC'
		Or Sub_SubjectName = 'PE 2' AND Sub_SubjectNo = 40
		Or Sub_SubjectName = 'GEC-MMW'
		Or Sub_SubjectName = 'GEC-KAF'
		Or Sub_SubjectName = 'PE 3' AND Sub_SubjectNo = 50
		Or Sub_SubjectName = 'GEC-PPTP'
		Or Sub_SubjectName = 'GEC-STS'
		Or Sub_SubjectName = 'GEC-US'
		Or Sub_SubjectName = 'PE 4' AND Sub_SubjectNo = 59
		Or Sub_SubjectName = 'GEE-FE'
		Or Sub_SubjectName = 'IM 326' AND Sub_SubjectNo = 1003
		Or Sub_SubjectName = 'IM 327' AND Sub_SubjectNo = 1004
		Or Sub_SubjectName = 'IM 328' AND Sub_SubjectNo = 1005
		Or Sub_SubjectName = 'CT 329'
		Or Sub_SubjectName = 'Fola 2'AND Sub_SubjectNo = 1007
		Or Sub_SubjectName = 'DT 329'
		Or Sub_SubjectName = 'ETECH 329'
		Or Sub_SubjectName = 'ELEX 326'
		Or Sub_SubjectName = 'CC 225'
		Or Sub_SubjectName = 'CC 225 L'
		Or Sub_SubjectName = 'P Elec 3'
		Or Sub_SubjectName = 'AP 3'
		Or Sub_SubjectName = 'MX - TECH 224'
		Or Sub_SubjectName = 'Mx 229'
		Or Sub_SubjectName = 'Mx 2210'
		Or Sub_SubjectName = 'CTC 222'
		Or Sub_SubjectName = 'GEE - GSPS'
		Or Sub_SubjectName = 'PC 315'
		Or Sub_SubjectName = 'PC 315L'
		Or Sub_SubjectName = 'PC 316'
		Or Sub_SubjectName = 'PC 317'
		Or Sub_SubjectName = 'CC 316'
		Or Sub_SubjectName = 'DTC 223'
		Or Sub_SubjectName = 'Draw 122' AND Sub_SubjectNo = 1078
		Or Sub_SubjectName = 'AST 122' AND Sub_SubjectNo = 1079
		Or Sub_SubjectName = 'DTech 122'
		Or Sub_SubjectName = 'ElcTech 122'
		Or Sub_SubjectName = 'PC 3210'
		Or Sub_SubjectName = 'PC 3211'
		Or Sub_SubjectName = 'PC 3211L'
		Or Sub_SubjectName = 'AP 4'
		Or Sub_SubjectName = 'AP 5'
		Or Sub_SubjectName = 'Mx-Tech 326'
		Or Sub_SubjectName = 'Mx 3214'
		Or Sub_SubjectName = 'Mx 3215'
		Or Sub_SubjectName = 'Mx-Mgt 322'
		Or Sub_SubjectName = 'ElcTech224'
		Or Sub_SubjectName = 'ETC 222'
		Or Sub_SubjectName = 'Draw 224' AND Sub_SubjectNo = 1138
		Or Sub_SubjectName = 'AST 224'
		Or Sub_SubjectName = 'DTech 224'
		Or Sub_SubjectName = 'DTC 222'
		Or Sub_SubjectName = 'CompTech 224'
		Or Sub_SubjectName = 'ElxTech 122'
		Or Sub_SubjectName = 'AP 2'
		Or Sub_SubjectName = 'GEE-IC'
		Or Sub_SubjectName = 'Mx-Mgt 321'
		Or Sub_SubjectName = 'Mx 3216'
		Or Sub_SubjectName = 'ElcTech 213'
		Or Sub_SubjectName = 'ETC 211'
		Or Sub_SubjectName = 'AST 213' AND Sub_SubjectNo = 1153
		Or Sub_SubjectName = 'ElcTech 315'
		Or Sub_SubjectName = 'IM 313' AND Sub_SubjectNo = '1155'
		Or Sub_SubjectName = 'AST 315'
		Or Sub_SubjectName = 'DTech 213'
		Or Sub_SubjectName = 'DTC 211'
		Or Sub_SubjectName = 'DTC 212'
		Or Sub_SubjectName = 'DTech 315'
		Or Sub_SubjectName = 'CompTech 213'
		Or Sub_SubjectName = 'CTC 211'
		Or Sub_SubjectName = 'CompTech 315'
		Or Sub_SubjectName = 'ElxTech 111'
		Or Sub_SubjectName = 'ElxTech 213'
		Or Sub_SubjectName = 'ElxC 211'
		Or Sub_SubjectName = 'Mx-Elec 311'
		Or Sub_SubjectName = 'Mx-Elec 312'
		Or Sub_SubjectName = 'Mx-Tech 315'
		Or Sub_SubjectName = 'Mx 3111'
		Or Sub_SubjectName = 'Mx 3112'
		Or Sub_SubjectName = 'Mx 3113'
		Or Sub_SubjectName = 'AP 1'
		Or Sub_SubjectName = 'PC 4112'
		Or Sub_SubjectName = 'PC 4112 L'
		Or Sub_SubjectName = 'PC 4113'
		Or Sub_SubjectName = 'PC Elec 4'
		Or Sub_SubjectName = 'AP 6'
		Or Sub_SubjectName = 'FoLa 1' AND Sub_SubjectNo = '1195'
		Or Sub_SubjectName = 'Draw 213' AND Sub_SubjectNo = 1196 OR Sub_SubjectNo = 1152 
		Or Sub_SubjectName = 'CC 123 L'
		Or Sub_SubjectName = 'GEE-LIE'
		Or Sub_SubjectName = 'MX 215'
		Or Sub_SubjectName = 'GEE-ES' AND Sub_SubjectNo = 288 OR Sub_SubjectNo = 811
		Or Sub_SubjectName = 'MX 217'
		Or Sub_SubjectName = 'CTC 223'
		Or Sub_SubjectName = 'Draw 111' AND Sub_SubjectNo = 649
		Or Sub_SubjectName = 'IM 311' AND Sub_SubjectNo = 1178 OR Sub_SubjectNo = 664
		Or Sub_SubjectName = 'IM 325'
		Or Sub_SubjectName = 'GEE-TEM'
		Or Sub_SubjectName = 'CC 111'
		Or Sub_SubjectName = 'CC 112'
		Or Sub_SubjectName = 'CC 112L'
		Or Sub_SubjectName = 'ElcTech 111'
		Or Sub_SubjectName = 'PC 121/Math-E 2'
		Or Sub_SubjectName = 'CompTech 111'
		Or Sub_SubjectName = 'DTech 111'
		Or Sub_SubjectName = 'CompTech 122'
		Or Sub_SubjectName = 'Comp 1' AND Sub_SubjectNo = 810
		Or Sub_SubjectName = 'MX - TECH 111'
		Or Sub_SubjectName = 'MX 111'
		Or Sub_SubjectName = 'MX 112'
		Or Sub_SubjectName = 'MX - Math 111'
		Or Sub_SubjectName = 'CC 123'
		Or Sub_SubjectName = 'MX-Tech 213'
		Or Sub_SubjectName = 'MX - TECH 122'
		Or Sub_SubjectName = 'MX 123'
		Or Sub_SubjectName = 'MX 124'
		Or Sub_SubjectName = 'MX - Math 122'
		Or Sub_SubjectName = 'MX 218'
		Or Sub_SubjectName = 'MX 216'
		Or Sub_SubjectName = 'PC 212'
		Or Sub_SubjectName = 'CC 214'
		Or Sub_SubjectName = 'CC 214 L'
		Or Sub_SubjectName = 'P Elec 1'
		Or Sub_SubjectName = 'P Elec 2'
		Or Sub_SubjectName = 'GEC- RPH'
		Or Sub_SubjectName = 'PC 224'
		Or Sub_SubjectName = 'AST 111'
		Or Sub_SubjectName = 'PC 223'
		Or Sub_SubjectName = 'IM 312' AND Sub_SubjectNo = 1179 OR Sub_SubjectNo = 923
		Or Sub_SubjectName = 'IM 314' AND Sub_SubjectNo = 925
		Or Sub_SubjectName = 'PC 329'
		
ORDER BY Sub_SubjectNo ASC
